Assignment 2
================
Leo Liu
Sept 24 2020

This is my solution to Assignment 2

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## Problem 1

Read the Mr. Trashwheel dataset

```{r}
trashwheel_df = 
   read_xlsx(
     "./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
     range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls)
  )
```

Read Precipitation data

```{r}
precip_2018 =
  read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "2018 Precipitation",
             skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2017 =
  read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "2017 Precipitation",
             skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Combine the two annual precipitation

```{r}
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df = 
  bind_rows(precip_2018, precip_2017)

left_join(precip_df, month_df, by = "month")
```

